"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Router = require("koa-router");
const system_1 = require("../models/system");
const router = new Router();
router.get('/system/email/season-start-barcodes', system_1.System.sendSeasonBarcodeReminders);
router.get('/system/waiver/search/:query', system_1.System.searchSystemSkaterWaivers);
router.get('/system/waiver/reference-number/:waiverReferenceNumber', system_1.System.getSystemSkaterWaiverByReferenceNumber);
router.get('/system/waiver/:waiverId', system_1.System.getSystemSkaterWaiverById);
router.get('/system/waiver', system_1.System.getSystemSkaterWaivers);
router.get('/system/pass/search/:query', system_1.System.searchSystemUserPasses);
router.get('/system/pass/:passId', system_1.System.getSystemPassById);
router.get('/system/pass', system_1.System.getSystemPasses);
router.get('/system/user/:userId', system_1.System.getSystemUserById);
router.get('/system/user', system_1.System.getSystemUserList);
router.get('/system/birthday/pizzas/:packageId', system_1.System.getNumberOfPackagePizzas);
router.get('/system/birthday/status', system_1.System.getBirthdayBookingStatuses);
router.get('/system/birthday/confirmation/:confirmationNumber', system_1.System.getBirthdayBookingByConfirmationNumber);
router.get('/system/birthday/:bookingId', system_1.System.getBirthdayBookingById);
router.get('/system/ticket/:id', system_1.System.getTicketById);
router.get('/system/ticket', system_1.System.getTickets);
router.get('/system/domo/id/:id', system_1.System.getDomoTicketById);
router.get('/system/domo', system_1.System.getDomoTickets);
router.get('/system/lesson/:id', system_1.System.getLessonById);
router.get('/system/lesson', system_1.System.getLessons);
router.get('/system/domo/:confirmationNumber', system_1.System.getDomoPassByConfirmationNumber);
router.get('/system/square/transaction/:transactionId', system_1.System.getSquareTransactionById);
router.get('/system/birthday-session', system_1.System.getBirthdaySessions);
router.post('/system/user', system_1.System.createSystemUser);
router.post('/system/search/user', system_1.System.searchSystemUsers);
router.post('/system/birthday/search', system_1.System.searchBirthdayBookings);
router.post('/system/birthday', system_1.System.addBirthdayBooking);
router.post('/system/ticket', system_1.System.searchTickets);
router.post('/system/domo', system_1.System.searchDomoTickets);
router.post('/system/lesson', system_1.System.searchLessons);
router.post('/system/ticket/master', system_1.System.updateMasterTicketInventory);
router.post('/system/pass/:confirmationNumber/log', system_1.System.logPassUsageWithConfirmationNumber);
router.post('/system/coupon', system_1.System.createCoupon);
router.put('/system/birthday/status', system_1.System.updateBirthdayStatus);
router.put('/system/birthday', system_1.System.updateBirthdayBooking);
router.put('/system/ticket/session', system_1.System.updateUserTicketSession);
router.put('/system/user', system_1.System.updateSystemUser);
router.put('/system/user/skater-waiver/:id', system_1.System.editSystemUserSkaterWaiverById);
router.put('/system/birthday-session', system_1.System.updateBirthdaySessionAvailability);
router.put('/system/coupon/:id', system_1.System.updateCoupon);
router.delete('/system/coupon/:id', system_1.System.deleteCouponById);
exports.default = router.routes();
