"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DEFAULT_MOMENT_FORMAT = 'MMM DD YYYY HH:mm';
exports.MOMENT_FORMAT_DATE = 'MMM DD YYYY';
exports.MOMENT_FORMAT_TIME = 'HH:mm';
exports.MOMENT_STORING_DATE = 'YYYY/MM/DD HH:mm';
exports.SQL_DATE_FORMAT = 'YYYY-MM-DD';
exports.SQL_DATETIME_FORMAT = 'YYYY-MM-DD HH:mm:ss';
exports.SQL_TIME_FORMAT = 'HH:mm:ss';
exports.MAX_SESSION_INVENTORY_COUNT = '160';
exports.ADULT_TICKET_VARIATION_NAME = 'Adult tickets';
exports.CHILD_TICKET_VARIATION_NAME = 'Child tickets';
exports.MASTER_VARIATION_NAME = 'Master ticket count';
exports.EMPLOYEE_ROLE = 2;
exports.ADMIN_ROLE = 3;
